name: CI/CD - Terraform + Docker + ECS

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2
      TF_VERSION: 1.9.7
      ECR_REPO_NAME: ecr-repo  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform init
        run: terraform -chdir=terraform init

      - name: Apply ECR only
        run: terraform -chdir=terraform apply -target=module.ecr.aws_ecr_repository.ecr_rep -auto-approve

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t my-memos:latest ./app/memos

      - name: Tag and push Docker image
        run: |
          image=my-memos:latest
          image_url1=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}
          docker tag $image $image_url1
          docker push $image_url1
          echo "IMAGE_URI=$image_url1" >> $GITHUB_ENV

      - name: Terraform Apply (Full Infrastructure)
        run: terraform -chdir=terraform apply -var-file="terraform.tfvars" -auto-approve
